### ISSUE TITLE
Cannot override a setting to a falsy value

### ISSUE THREAD

**Issue by adriantoine** [danreeves/sublime-prettier#13]
Sorry that's me again 😊

I'm trying the plugin with these settings:
```json
{
    "extensions": ["js"],
    "autoformat": true,
    "singleQuote": true,
    "bracketSpacing": false
}
```
but the command is actually run with these options:
```
['--print-width', '80', '--tab-width', '2', '--single-quote']
```
the `bracketSpacing` is not being set to `false`, so `prettier` will use the default value, which is `true`.

The correct options are:
```
['--print-width', '80', '--tab-width', '2', '--single-quote', 'true', '--bracket-spacing', 'false']
```

It is due to that condition: https://github.com/danreeves/sublime-prettier/blob/d333f51897ae827bbdf5b69b9627fdea6ae0d813/prettier.py#L23 so falsy setting values won't be set at all.

**Comment by danreeves** [comment]
You're right. Looks like this is an odd one out in the commands; they should have implemented it as `--no-bracket-spacing` really. 

I think the best way will just be to special case bracket spacing.

**Comment by adriantoine** [comment]
The other solution is to append boolean values as shown in my example:
```
['--single-quote', 'true', '--bracket-spacing', 'false']
```
it would set `bracketSpacing` to `false` and `singleQuote` to `true`, so we don't really have to handle a special case there, just to append all boolean values like the other ones.

**Comment by danreeves** [comment]
You're right, that works and makes the code a bit simpler. I just noticed a bug with the options getting cached too 👍 . Fix incoming
