### ISSUE TITLE
Does not respect settings in ST3

### ISSUE THREAD

**Issue by joshuapaling** [danreeves/sublime-prettier#16]
I'm using the recently-released Sublime Text v3 (not the beta).

I've tried `"singleQuote": true,` in both the user settings, and the default settings. In both cases, it'll still switch my quotes to double quotes on save. It didn't used to do this - it used to work as expected. I think the "break" might have came when I updated from ST3 beta to the real v3 release.

I've tried uninstalling and re-installing the package.

If I manually run `prettier --single-quote --trailing-comma es5  --write ./my/file.js` it works as expected.

PS - it'd be awesome if this plugin respected the `.prettierrc` file.

**Comment by danreeves** [comment]
Hey @joshuapaling,

There's another, better supported, plugin here: https://packagecontrol.io/packages/JsPrettier

I'd recommend using that.

Cheers
